#!/bin/bash

###############################
#
# Monit 5.3.1
# http://mmonit.com/monit/
#
# Configuration files
# vi /etc/monitrc
#
###############################

# Dependancies
yum install flex bison openssl-devel;

# Installation
cd /usr/local/src;
wget http://mmonit.com/monit/dist/monit-5.3.1.tar.gz;
echo '91a3f15c11a9b9e60e6e3b963f9f4af2acf5ca50ac6dc047d94ce50e966addc6  monit-5.3.1.tar.gz' | sha256sum -c;
tar -xvzf monit-5.3.1.tar.gz && cd monit-5.3.1;
./configure;
make && make install;

# Settings file
touch /etc/monitrc;
chmod 600 /etc/monitrc;

# Run on system startup and start now
echo '/usr/local/bin/monit -c /etc/monitrc -p /var/run/monit.pid' >> /etc/rc.local;
/usr/local/bin/monit -c /etc/monitrc -p /var/run/monit.pid;
