#!/bin/bash

###############################
#
# Boost C++ Libraries 1.48.0
# http://www.boost.org/
#
###############################

# followed this guide
# http://ubuntuforums.org/showthread.php?t=1180792

# might need this
sudo apt-get install libbz2-dev;

wget http://downloads.sourceforge.net/project/boost/boost/1.48.0/boost_1_48_0.tar.gz;
tar -xvzf boost_1_48_0.tar.gz && cd boost_1_48_0/;

./bootstrap.sh --with-libraries=filesystem,regex,program_options,system --exec-prefix=/usr/local;

./b2;

sudo ./b2 install;

sudo ldconfig;

# link libraries by using -lboost_regex in LFLAGS
