#!/bin/bash

###############################
#
# Dovecot 2.0.17
# http://www.dovecot.org/download.html
#
# Config Files
# vi /etc/dovecot/*.conf
#
# Note: This script expects the Postfix script to be run first
#
###############################


# Remove Dovecot if previously installed
monit unmonitor dovecot;
/etc/init.d/dovecot stop;
chkconfig --del dovecot;
yum remove dovecot;

# Dependencies
yum install gcc gettext-devel;

# Get public key to verify PGP keys
gpg --recv-keys --keyserver hkp://wwwkeys.pgp.net 0x40558AC9;

# Download, compile and install
cd /usr/local/src;
wget http://www.dovecot.org/releases/2.0/dovecot-2.0.17.tar.gz;
wget http://www.dovecot.org/releases/2.0/dovecot-2.0.17.tar.gz.sig;
gpg --verify dovecot-2.0.17.tar.gz.sig dovecot-2.0.17.tar.gz;
tar -xvzf dovecot-2.0.17.tar.gz && cd dovecot-2.0.17;
./configure --sysconfdir=/etc --with-mysql --libdir=/usr/lib64;
make;
make install;

# Setup Dovecot user
/usr/sbin/useradd -s /sbin/nologin -r dovecot;
# Dovecot user for completely untrustworthy processes
/usr/sbin/useradd -s /sbin/nologin -r dovenull;

# Secure devecot config files
chmod 600 /etc/dovecot/dovecot*.conf;
chown root:root /etc/dovecot/*;

touch /var/log/dovecot-deliver.log;
touch /var/log/dovecot-deliver-errors.log;
chmod 666 /var/log/dovecot-deliver*;

# Init script
wget https://raw.github.com/sbarakat/scripts/master/vps-scripts/dovecot-init.d -O /etc/init.d/dovecot;
chown root:root /etc/init.d/dovecot;
chmod 755 /etc/init.d/dovecot;

# Run on system startup and start now
/sbin/chkconfig --levels 235 dovecot on;
/etc/init.d/dovecot start;


####
# Adding Pigeonhole 0.2.5
# http://pigeonhole.dovecot.org/download.html
#

gpg --recv-keys --keyserver hkp://wwwkeys.pgp.net 0x3DFBB4F4;
cd /usr/local/src;
wget http://www.rename-it.nl/dovecot/2.0/dovecot-2.0-pigeonhole-0.2.5.tar.gz;
wget http://www.rename-it.nl/dovecot/2.0/dovecot-2.0-pigeonhole-0.2.5.tar.gz.sig;
gpg --verify dovecot-2.0-pigeonhole-0.2.5.tar.gz.sig dovecot-2.0-pigeonhole-0.2.5.tar.gz;
tar -xvzf dovecot-2.0-pigeonhole-0.2.5.tar.gz && cd dovecot-2.0-pigeonhole-0.2.5;
./configure --with-dovecot=/usr/lib64/dovecot;
make && make install;

# Add this to dovecot.conf
protocol lda {
    postmaster_address = postmaster@example.com
    hostname = mail.example.com
    mail_plugins = pigeonhole

    log_path = /var/log/dovecot-deliver-errors.log
    info_log_path = /var/log/dovecot-deliver.log

    #debug = yes

    sieve_global_path = /var/spool/sieve/dovecot.sieve
    mail_plugin_dir = /usr/local/lib/dovecot/lda
    auth_socket_path = /var/run/dovecot/auth-master
}

plugin {
    sieve = ~/.dovecot.sieve
}

auth default {
    mechanisms = plain

    passdb sql {
        args                    = /etc/dovecot-mysql.conf
    }
    userdb sql {
        args                    = /etc/dovecot-mysql.conf
    }

    socket listen {
        master {
            path = /var/run/dovecot/auth-master
            mode = 0660
            user = vmail
        }

        # This part should already be here
        client {
            user = postfix
            group = postfix
            path = /var/spool/postfix/private/auth
            mode = 0660
        }
    }
}


# Add this to the bottom of /etc/postfix/master.cf
dovecot   unix  -       n       n       -       -       pipe
  flags=DRhu user=vmail:mail argv=/usr/local/libexec/dovecot/deliver -f ${sender} -d ${recipient}

# Change this setting in /etc/postfix/main.cf
#virtual_transport                       = virtual
virtual_transport                       = dovecot

# Restart the services
/etc/init.d/postfix restart;
/etc/init.d/dovecot restart;
