#!/bin/bash

###############################
#
# Monit 5.5
# http://mmonit.com/monit/
#
# Configuration files
# vi /etc/monitrc
#
###############################

# Dependancies
yum install flex bison openssl-devel;

# Installation
cd /usr/local/src;
wget http://mmonit.com/monit/dist/monit-5.5.tar.gz;
echo '8276b060b3f0e6453c9748d421dec044ddae09d3e4c4666e13472aab294d7c53  monit-5.5.tar.gz' | sha256sum -c;
tar -xvzf monit-5.5.tar.gz && cd monit-5.5;
./configure --without-pam;
make && make install;

# Settings file
wget https://raw.github.com/sbarakat/scripts/master/vps-scripts/monit-monitrc -O /etc/monitrc;
chown root:root /etc/monitrc;
chmod 600 /etc/monitrc;
vi /etc/monitrc;

# Run on system startup and start now
echo '/usr/local/bin/monit -c /etc/monitrc -p /var/run/monit.pid' >> /etc/rc.local;
/usr/local/bin/monit -c /etc/monitrc -p /var/run/monit.pid;
