#!/bin/bash

###############################
#
# Nginx 1.0.14
# http://nginx.org/ 
#
# Configuration files
# vi /etc/nginx/*
#
###############################

# Dependencies
yum install gcc make autoconf automake zlib-devel openssl-devel pcre pcre-devel;

# Get public key to verify PGP keys
gpg --recv-keys --keyserver hkp://wwwkeys.pgp.net 0xA1C052F8;

# Download, compile and install
cd /usr/local/src;
wget http://nginx.org/download/nginx-1.0.14.tar.gz;
wget http://nginx.org/download/nginx-1.0.14.tar.gz.asc;
gpg --verify nginx-1.0.14.tar.gz.asc;
tar -xvzf nginx-1.0.14.tar.gz && cd nginx-1.0.14;
./configure --prefix=/usr/local/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --pid-path=/var/run/nginx.pid \
    --http-log-path=/var/log/nginx/access.log \
    --error-log-path=/var/log/nginx/error.log \
    --sbin-path=/usr/local/sbin/nginx \
    --user=nginx --group=nginx \
    --with-http_ssl_module \
    --without-mail_pop3_module \
    --without-mail_imap_module \
    --without-mail_smtp_module;
make && make install;

# Setup nginx user
/usr/sbin/useradd -s /sbin/nologin -r nginx;

# Init script
wget https://raw.github.com/sbarakat/scripts/master/vps-scripts/nginx-init.d -O /etc/init.d/nginx;
chown root:root /etc/init.d/nginx;
chmod 755 /etc/init.d/nginx;

# Start on start up
/sbin/chkconfig --add nginx;
/sbin/chkconfig --level 2345 nginx on;
service nginx start;

ln -s /usr/local/sbin/nginx /usr/sbin/nginx;
