#!/bin/bash

###############################
#
# Nginx 1.0.11
# http://nginx.org/ 
#
# Configuration files
# vi /etc/nginx/*
#
###############################

# Dependencies
yum install gcc make autoconf automake zlib-devel openssl-devel pcre pcre-devel;

# Download, compile and install
cd /usr/local/src;
wget http://nginx.org/download/nginx-1.0.11.tar.gz;
tar -xvzf nginx-1.0.11.tar.gz && cd nginx-1.0.11;
./configure --prefix=/usr/local/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --pid-path=/var/run/nginx.pid \
    --http-log-path=/var/log/nginx/access.log \
    --error-log-path=/var/log/nginx/error.log \
    --sbin-path=/usr/local/sbin/nginx \
    --user=nginx --group=nginx \
    --with-http_ssl_module \
    --without-mail_pop3_module \
    --without-mail_imap_module \
    --without-mail_smtp_module;
make && make install;

# Setup nginx user
/usr/sbin/useradd -s /sbin/nologin -r nginx

# Init script
wget https://raw.github.com/sbarakat/scripts/master/vps-scripts/nginx-init -O /etc/init.d/nginx;
chmod 755 /etc/init.d/nginx;

# Start on start up
/sbin/chkconfig --add nginx
/sbin/chkconfig --level 2345 nginx on
/etc/init.d/nginx start

ln -s /usr/local/sbin/nginx /usr/sbin/nginx
